apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rabbitmq-ui
  namespace: zttl-uat
spec:
  rules:
  - host: rabbitmq.dev.chinacrt.com
    http:
      paths:
      - path: /
        backend:
          serviceName: rabbitmq-rabbitmq
          servicePort: 15672

