apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: graylog-deploy
  labels:
    service: graylog-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: graylog-deploy
    spec:
      containers:
      - name: graylog3
        image: graylog/graylog:3.0
        env:
        - name: GRAYLOG_PASSWORD_SECRET
          value: g0ABP9MJnWCjWtBX9JHFgjKAmD3wGXP3E0JQNOKlquDHnCn5689QAF8rRL66HacXLPA6fvwMY8BZoVVw0JqHnSAZorDDOdCk
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: 36c3d6a455d1be9bcbb24bb54d9fe59bfbbc84c766df434882a31256a7e2dfe3
        - name: GRAYLOG_HTTP_EXTERNAL_URI
          value: http://graylog.dev.chinacrt.com:23456/
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          value: http://elasticsearch-service:9200
        - name: GRAYLOG_MONGODB_URI
          value: mongodb://mongo:27017/graylog
        ports:
        - containerPort: 9000
        - containerPort: 12201

---
apiVersion: v1
kind: Service
metadata:
  name: graylog3
spec:
  type: NodePort
  selector:
    service: graylog-deploy
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
    nodePort: 26666
  - name: "12201"
    port: 12201
    targetPort: 12201
    nodePort: 26667

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 labels:
   app: graylog
 name: graylog
 namespace: default
spec:
 rules:
   - host: graylog.dev.chinacrt.com
     http:
       paths:
         - backend:
             serviceName: graylog3
             servicePort: 9000

