apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alicloud-nas-zttl
mountOptions:
- vers=4
provisioner: alicloud/nas
reclaimPolicy: Retain

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: alicloud-nas-controller
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: alicloud-nas-controller
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        operator: Exists
        key: node.cloudprovider.kubernetes.io/uninitialized
     # nodeSelector:
     #   node-role.kubernetes.io/master: ""
      serviceAccount: admin-user
      containers:
        - name: alicloud-nas-controller
          image: registry.cn-shenzhen.aliyuncs.com/acs/alicloud-nas-controller:v3.1.0-k8s1.11
          volumeMounts:
          - mountPath: /persistentvolumes
            name: nfs-client-root
          env:
            - name: PROVISIONER_NAME
              value: alicloud/nas
            - name: NFS_SERVER
              value: 147004a83f-esj83.cn-beijing.nas.aliyuncs.com
            - name: NFS_PATH
              value: /storageclass-zttl
      volumes:
      - name: nfs-client-root
        flexVolume:
          driver: "alicloud/nas"
          options:
            path: "/storageclass-zttl"
            server: "147004a83f-esj83.cn-beijing.nas.aliyuncs.com"
            vers: "4.0"
