---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ceui
  name: redis-sc
  annotations:
    volume.beta.kubernetes.io/storage-class: "alicloud-nas-ceui"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-sc
  namespace: ceui
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
      labels:
        app: redis-sc
    spec:
      containers:
      - name: redis-sc
        image: redis:5.0
        volumeMounts:
        - mountPath: /data
          name: redis-data
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
      - name: redis-sc-exporter
        image: oliver006/redis_exporter:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9121
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-sc

---
kind: Service
apiVersion: v1
metadata:
  name: redis-sc
  namespace: ceui
spec:
  type: NodePort
  selector:
    app: redis-sc
  ports:
  - name: redis-sc
    port: 6379
    targetPort: 6379
  - name: prom-sc
    port: 9121
    targetPort: 9121

